name: Pack extension
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: linux
    steps:
      - uses: actions/checkout@v2

      - name: Setup GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.4.0

      - name: Setup Ninja
    		uses: seanmiddleditch/gha-setup-ninja@master

      - name: Run Example Build Script
        run: |
          chmod +x ./test-build-examples.sh
          ./test-build-examples.sh

